project/home/urls.py
"""
urls.py
This module defines the URL patterns for the Home application. It maps views and functionalities to their respective routes 
to ensure proper navigation and interaction within the application.
Routes included:
    - Authentication: Handles login, logout, registration, account updates, and password updates.
    - Calendar: Provides calendar views (monthly, weekly) and event management (create, edit, delete, detail view).
    - Games: Allows for game creation, editing, and association with events.
    - Friend Requests: Includes functionalities for sending, accepting, declining, and managing friend requests.
    - Calendar Sharing: Implements token-based calendar sharing and access.
    - Search: Provides endpoints for standard and AJAX-based user and friend searches.
    - Media: Configures media handling for image uploads during development.
Features:
    - Integrates Django's built-in authentication system.
    - Implements custom views for extended functionalities, such as custom logout and user registration.
    - Supports dynamic routes with user IDs, event IDs, and game IDs for specific operations.
Setup:
    - Uses Django's `path` and `re_path` utilities for URL mapping.
    - Includes static file handling for development environments using `settings.MEDIA_URL` and `settings.MEDIA_ROOT`.
Notes:
    - All AJAX endpoints are clearly labeled to distinguish them from standard views.
    - Routes are modular and intuitive to support easy navigation and future scalability.
"""

from django.urls import path, re_path, include
from . import views
from .views import *
from .forms import CustomPasswordChangeForm, CustomUserCreationForm, EventForm, Game, UsersForm
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth
from django.urls import path, re_path, include


urlpatterns = [
    path("", index, name="index"),
    # include home path on url to match our navbar route
    path("home", index, name="home"),
    # login/registration urls
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/logout/", CustomLogoutView, name="logout"),  # Use your custom logout view
    path("accounts/register/", register, name="register"),
    path("accounts/profile/", views.userPage, name="user_page"),
    path("accounts/update_password/", views.update_password, name="update_password"),
    path("accounts/update_account/", views.update_account, name="update_account"),
    path("calendar/<int:user_id>/", CalendarView.as_view(), name="calendar"),
    re_path(r"^event/new/$", views.event, name="event_new"),
    re_path(r"^event/edit/(?P<event_id>\d+)/$", views.event, name="event_edit"),
    # Add URL path for the event detail view
    path("event/<int:event_id>/", views.event_detail, name="event_detail"),
    # URL path for game list
    path("calendar/games/", views.game_list, name="game_list"),
    # URl path for the create game view
    path("games/create_game/", views.create_game, name="create_game"),
    # URL for editing an existing game
    path("games/<int:game_id>/edit/", views.create_game, name="edit_game"),
    # URL for deleting an exisitng game
    path("games/<int:game_id>/delete/", views.delete_game, name="delete_game"),
    # url for event deletion that takes in user id and event id
    path("event_delete/<int:user_id>/<int:id>", views.deleteEvent, name="delete_event"),
    path("todo-list/", views.todo_list, name="todo_list"),
    # Standard search page
    path("friends/", views.friends, name="friends"),
    path("view_friends/", views.view_friends, name="view_friends"),
    path(
        "ajax_view_friends/", views.ajax_view_friends, name="ajax_view_friends"
    ),  # AJAX friends endpoint
    path("search/", views.ajax_search, name="ajax_search"),  # AJAX search endpoint
    # path to generate link with token
    path("generate_calendar_link/", views.generate_calendar_link, name="generate_calendar_link"),
    # path to grant access based on token
    path("calendar/access/", views.calendar_access, name="view_shared_calendar"),
    # handling Friend requests
    path("send_friend_request/", views.send_friend_request, name="send_friend_request"),
    path("friend-requests/", views.view_friend_requests, name="view_friend_requests"),
    path("ajax/friend-requests/", views.ajax_friend_requests, name="ajax_friend_requests"),
    path("accept-friend-request/", views.accept_friend_request, name="accept_friend_request"),
    path("decline-friend-request/", views.decline_friend_request, name="decline_friend_request"),
    path("delete_friend/", views.delete_friend, name="delete_friend"),
]

# stuff for image upload
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/mutants/project/urls.py
from inspect import signature as _mutmut_signature

def _mutmut_trampoline(orig, mutants, *args, **kwargs):
    import os
    mutant_under_test = os.environ['MUTANT_UNDER_TEST']
    if mutant_under_test == 'fail':
        from mutmut.__main__ import MutmutProgrammaticFailException
        raise MutmutProgrammaticFailException('Failed programmatically')      
    elif mutant_under_test == 'stats':
        from mutmut.__main__ import record_trampoline_hit
        record_trampoline_hit(orig.__module__ + '.' + orig.__name__)
        result = orig(*args, **kwargs)
        return result  # for the yield case
    prefix = orig.__module__ + '.' + orig.__name__ + '__mutmut_'
    if not mutant_under_test.startswith(prefix):
        result = orig(*args, **kwargs)
        return result  # for the yield case
    mutant_name = mutant_under_test.rpartition('.')[-1]
    result = mutants[mutant_name](*args, **kwargs)
    return result


from inspect import signature as _mutmut_signature

def _mutmut_yield_from_trampoline(orig, mutants, *args, **kwargs):
    import os
    mutant_under_test = os.environ['MUTANT_UNDER_TEST']
    if mutant_under_test == 'fail':
        from mutmut.__main__ import MutmutProgrammaticFailException
        raise MutmutProgrammaticFailException('Failed programmatically')      
    elif mutant_under_test == 'stats':
        from mutmut.__main__ import record_trampoline_hit
        record_trampoline_hit(orig.__module__ + '.' + orig.__name__)
        result = yield from orig(*args, **kwargs)
        return result  # for the yield case
    prefix = orig.__module__ + '.' + orig.__name__ + '__mutmut_'
    if not mutant_under_test.startswith(prefix):
        result = yield from orig(*args, **kwargs)
        return result  # for the yield case
    mutant_name = mutant_under_test.rpartition('.')[-1]
    result = yield from mutants[mutant_name](*args, **kwargs)
    return result


"""
URL configuration for project project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include



#Map a URL to a view, and 'include' allows referencing other URL configuration modules
urlpatterns = [
    # Maps the URL 'admin/' to Django's built-in admin interface
    path('admin/', admin.site.urls),
    # Maps the URL 'proxy/3000/' to the URL configurations defined in 'home.urls'
    path('proxy/3000/', include('home.urls')),
    path('', include('home.urls')),
    #path('/calendar', CalendarView.as_view(), name = 'calendar' ),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include



#Map a URL to a view, and 'include' allows referencing other URL configuration modules
urlpatterns = [
    # Maps the URL 'admin/' to Django's built-in admin interface
    path('admin/', admin.site.urls),
    # Maps the URL 'proxy/3000/' to the URL configurations defined in 'home.urls'
    path('proxy/3000/', include('home.urls')),
    path('', include('home.urls')),
    #path('/calendar', CalendarView.as_view(), name = 'calendar' ),

]

project/home/models.py
"""
models.py

This module contains the database models used in the application. The models define the structure of the application's
data and include methods for interacting with the database.

Models:
    - Game: Represents a game in the system, including details like name, genre, platform, and associated images.
    - Event: Represents an event in the system, including its details, recurrence patterns, and associations with users and games.
    - FriendRequest: Represents a friend request between users, supporting accepted and pending requests.
    - CalendarAccess: Represents a token-based system to share access to a user's calendar.

Features:
    - Supports recurring events (daily, weekly, monthly) with an optional end date.
    - Provides permission-based access to events using the `guardian` library.
    - Manages relationships between users through friend requests.
    - Enables calendar sharing via unique tokens.
"""

from django.db import models
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.shortcuts import reverse
from guardian.shortcuts import assign_perm
import uuid

# Create your models here.


# Game model
class Game(models.Model):
    """
    Represents a game unique to each user.

    Attributes:
        name (str): Name of the game.
        genre (str): Genre of the game (optional).
        platform (str): Gaming platform (e.g., PC, PlayStation).
        developer (str): Developer of the game (optional).
        release_date (date): Release date of the game (optional).
        color (str): Color code associated with the game (e.g., for UI purposes).
        picture_link (str): URL to the game's image (optional).
        picture_upload (ImageField): Optional uploaded image for the game.
        user (User): The user who owns this game instance.
    """

    PLATFORM_CHOICES = [
        ("PC", "PC"),
        ("PS", "PlayStation"),
        ("XBOX", "Xbox"),
        ("NS", "Nintendo Switch"),
    ]
    COLOR_CHOICES = [
        ("#FF5733", "Red"),
        ("#FFA500", "Orange"),
        ("#FFFF33", "Yellow"),
        ("#33FF57", "Green"),
        ("#3357FF", "Blue"),
        ("#FF33FF", "Pink"),
        ("#800080", "Purple"),
    ]
    name = models.CharField(max_length=200)
    genre = models.CharField(max_length=100, blank=True, null=True)
    platform = models.CharField(max_length=50, choices=PLATFORM_CHOICES, blank=True, null=True)
    developer = models.CharField(max_length=100, blank=True, null=True)
    release_date = models.DateField(blank=True, null=True)
    color = models.CharField(
        max_length=7, choices=COLOR_CHOICES, default="#FFFFFF"
    )  # Set default color
    picture_link = models.CharField(max_length=1000, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="games")

    # adding in this so peopel can upload pictures
    picture_upload = models.ImageField(blank=True, null=True)

    def __str__(self):
        """
        Returns the string representation of the game.
        """
        return self.name


# Event model
class Event(models.Model):
    """
    Represents an event in the system.

    Attributes:
        title (str): Title of the event.
        description (str): Detailed description of the event.
        start_time (datetime): When the event starts.
        end_time (datetime): When the event ends.
        user (User): The user associated with the event.
        recurrence (str): Recurrence pattern of the event (none, daily, weekly, monthly).
        recurrence_end (date): Optional end date for recurring events.
        priority (int): Priority level of the event (1=Low, 2=Medium, 3=High).
        game (Game): Optional game associated with the event.
    """

    PRIORITY_CHOICES = [
        (1, "Low"),
        (2, "Medium"),
        (3, "High"),
    ]

    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, default=None)
    ############### This is where recurring choices being implemented #################
    RECURRING_CHOICES = [
        ("none", "None"),
        ("daily", "Daily"),
        ("weekly", "Weekly"),
        ("monthly", "Monthly"),
    ]

    recurrence = models.CharField(max_length=20, choices=RECURRING_CHOICES, default="none")
    recurrence_end = models.DateField(blank=True, null=True)  # End date for the recurrence

    class Meta:
        permissions = [("saved_events", "can save events")]

    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=2)
    game = models.ForeignKey(
        Game, on_delete=models.CASCADE, related_name="events", null=True, blank=True
    )

    @property
    def get_html_url(self):
        """
        Generates the URL for the event's detail page and returns it as an HTML anchor tag.
        """
        # Return the event_detail link for the event
        url = reverse("event_detail", args=(self.id,))
        # Override default url settings, make font black for readability
        return f'<a href="{url}" style="color: #000;">{self.title}</a>'

    def save(self, *args, **kwargs):
        """
        Overrides the default save method to assign view permissions to the user.
        """
        super().save(*args, **kwargs)
        # Grant 'view_event' permission to the assigned user
        assign_perm("view_event", self.user, self)

    def __str__(self):
        """
        Returns the string representation of the event.
        """
        return self.title


User = get_user_model()


class FriendRequest(models.Model):
    """
    Represents a friend request between users.

    Attributes:
        from_user (User): The user who sent the request.
        to_user (User): The user who received the request.
        created_at (datetime): When the friend request was created.
        accepted (bool): Whether the request has been accepted.
    """

    from_user = models.ForeignKey(User, related_name="sent_requests", on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name="received_requests", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)

    def __str__(self):
        """
        Returns a string representation of the friend request.
        """
        return f"{self.from_user.username} to {self.to_user.username}"

    @property
    def friends(self):
        """
        Returns a queryset of all accepted friends for the current user.
        """
        # Get users who have accepted friend requests in either direction
        friends = User.objects.filter(
            Q(
                id__in=FriendRequest.objects.filter(
                    from_user=self.from_user, accepted=True
                ).values_list("to_user", flat=True)
            )
            | Q(
                id__in=FriendRequest.objects.filter(
                    to_user=self.from_user, accepted=True
                ).values_list("from_user", flat=True)
            )
        ).exclude(
            id=self.from_user.id
        )  # Exclude the current user

        return friends


class CalendarAccess(models.Model):
    """
    Represents a token-based system to share access to a user's calendar.

    Attributes:
        user (User): The user whose calendar is being shared.
        token (UUID): Unique token for identifying the shared calendar.
        created_at (datetime): When the calendar access was created.
    """

    user = models.ForeignKey(User, related_name="calendar_access", on_delete=models.CASCADE)
    token = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Returns a string representation of the calendar access instance.
        """
        return f"Access for {self.user.username} - {self.token}"

project/home/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
    <!-- ensure that static folder is available for use on this template -->
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Used bootstrap to make sure sticky navigation bar with game-logo on the left and routes to other pages -->
    <link rel="stylesheet" href="{% static 'styles-v2.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
    <title>
        {% block title %}Homepage
        {% endblock %}
    </title>
    
</head>
<body class="d-flex flex-column min-vh-100">
    
    <!-- including common navbar file on index page  -->
    <!-- Updated navigation for responsiveness w/ better view -->
    <nav class="nav navbar navbar-expand-lg navbar-dark sticky-top" >
        <div class="container-fluid">
            <!-- logo -->
            <img src="{% static 'images/game-logo.png' %}" alt="GamePlan Logo" class="logo">
            <!-- toggle navigation for the small screen sizes for responsiveness -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav" >
                <div class="mx-auto"> <!-- This centers the navbar items -->
                    <!-- navigation list -->
                    <ul class="navbar-nav">
                        <li class="nav-item active"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                        {% if user.is_authenticated %}
                        <!-- Calendar-->
                        <li class="nav-item active"><a class="nav-link" href="{% url 'calendar' user.id %}">Calendar</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'todo_list' %}">To-Do List</a></li>
                    
                            <li class="nav-item"><a class="nav-link" href="{% url 'user_page' %}">Account</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                        {%endif%}

                        <!-- Theme Toggle -->
                        <li class="nav-item">
                            <div class="form-check form-switch d-flex align-items-center">
                                <input class="form-check-input d-none" type="checkbox" id="theme-toggle" onchange="toggleTheme()">
                                <label class="form-check-label m-0" for="theme-toggle">
                                    <span id="theme-icon" class="material-icons" style="cursor: pointer;">light_mode</span>
                                </label>
                            </div>
                        </li> 
                    </ul>
                
                
                </div> 
            </div>
        </div>
    </nav>
    <!-- Page Content -->
    <div class="flex-grow-1" id = "content"> 
        {% block content %}{% endblock %}
    </div>

    {% block scripts %}
    {% endblock %}

    {% block footer %}
    <footer class="footer mt-auto">
        <div class="container text-center">
            <p>Created by Group 2</p>
        </div>
    </footer>
    {% endblock %}

    
    
<!-- Bootstrap and jQuery JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
<!-- Theme toggle script -->
<script>
    
    function toggleTheme() {
        const body = document.body;
        const currentTheme = body.getAttribute('data-theme');

        // Toggle the theme
        const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
        body.setAttribute('data-theme', newTheme);

        // Update the icon
        const themeIcon = document.getElementById('theme-icon');
        themeIcon.textContent = newTheme === 'dark' ? 'light_mode' : 'brightness_2'; // Bright moon for light mode
        
        // Save preference to localStorage
        localStorage.setItem('theme', newTheme);
    }

    // Check local storage for theme preference on page load
    document.addEventListener('DOMContentLoaded', () => {
        const savedTheme = localStorage.getItem('theme') || 'light'; // Default to light
        document.body.setAttribute('data-theme', savedTheme);

        // Set the toggle icon based on the saved theme
        const themeIcon = document.getElementById('theme-icon');
        themeIcon.textContent = savedTheme === 'dark' ? 'light_mode' : 'brightness_2'; // Bright moon for light mode
    });


</script>
<style>
    /* Dark and Light Theme Styles */
    body[data-theme='light'] {
        background-color: #ffffff; /* Light background */
        color: #000000; /* Dark text */
    }

    body[data-theme='dark'] {
        background-color: #000000; /* Dark background */
        color: #ffffff; /* Light text */
    }

    #theme-icon {
        font-size: 1.5em;
        color: #ffffff;
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0;
        padding: 0;
    }

    .form-check.form-switch {
        display: flex;
        align-items: center;
        margin: 0;
        justify-content: center;
        padding: 0;
        height: 100%;
    }

    .nav-item .form-check-label {
        margin: 0;
    }

    .navbar-nav .nav-item {
        display: flex;
        align-items: center;
    }

    .navbar {
        min-height: 56pxx;
    }

    
</style>
</div>
</body>
</html>

project/home/templates/confirm_delete.html
{% extends "base_template.html" %}

<head>
    {% load static %} <!-- Load the static tag library -->
    {% block title %}Delete Game{% endblock %}
</head>

{% block content %}
<div class="container-fluid d-flex justify-content-center align-items-center" style="height: 75vh;">
    <div class="text-center">
        <h5><b>Are you sure you want to delete "{{ game.name }}"?</b></h5>

        <form action="" method="POST">
            {% csrf_token %}
            <a class="btn me-2" href="{% url 'game_list' %}">Cancel</a>
            <button class="btn" type="submit" style="background-color: red !important;">Confirm</button>
        </form>
    </div>
</div>
{% endblock %}

project/home/templates/create_game.html
{% extends "base_template.html" %}

{% block title %}
    {% if form.instance.id %}Edit Game{% else %}Create Game{% endif %}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center">
        {% if form.instance.id %}Edit Game{% else %}Create New Game{% endif %}
    </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <a class="btn mt-3" href="{% url 'game_list'%}">Back to Game List</a>
        <button type="submit" class="btn mt-3">
            {% if form.instance.id %}Update Game{% else %}Create Game{% endif %}
        </button>
        
    </form>
</div>
{% endblock %}

project/home/templates/delete.html
<!--Inheret from base template-->
{% extends "base_template.html" %} 

<head>
    {% load static %}  <!-- Load the static tag library -->

    {% block title %}Event Details{% endblock %}
</head>
{% block content %}

<div class="container-fluid d-flex justify-content-center align-items-center" style="height: 75vh;">
    <div class="text-center">
        <h5><b>Are you sure you want to delete "{{ event.title }}"?</b></h5>
        
        <form action="" method="POST">
            {% csrf_token %}
            <a class="btn me-2" href="{% url 'event_detail' event.id %}">Cancel</a>
            <button class="btn" type="submit" style="background-color: red !important;">Confirm</button>
        </form>
    </div>
</div>

</div>
{% endblock %}

project/home/templates/event_detail.html
{% extends "base_template.html" %} 

<head>
    {% load static %}  <!-- Load the static tag library -->


    <link rel="stylesheet" type="text/css" href="{% static 'calendar/styles.css' %}">

    {% block title %}Event Details{% endblock %}
</head>

{% block content %}


<body>

    <div class="container mt-4">
        <h1>{{ event.title }}</h1>
        <p>{{ event.description }}</p>
        <p><strong>Start Time:</strong> {{ event.start_time }}</p>
        <p><strong>End Time:</strong> {{ event.end_time }}</p>
        <!-- Display priority -->
        <p><strong>Priority:</strong> {{ event.get_priority_display }}</p>
        <!-- Display associated game -->
        <p><strong>Video Game:</strong> {{ event.game.name }}</p>
        <p><strong>Platform:</strong> {{ event.game.get_platform_display }}</p>
        <p><strong>Genre:</strong> {{ event.game.genre }}</p>
        <div class='d-flex' style="max-width: 100%; height: auto;" >
            {% if event.game.picture_upload %}
                <img src="{{ event.game.picture_upload.url }}" style="display: block;"/>
            {% elif event.game.picture_link %}
                <img src="{{ event.game.picture_link }}" alt="Image for {{ event.game.name }}" style="display: block;" />
            {% else %}
                <img src="{% static 'images/game-icon.jpg' %}" alt="Default game image" class="game-image" style="display: block;" />
            {% endif %}
        </div>
            
        <!-- Buttons for back to calendar and edit event -->
        <div class="clearfix">
            <a class="btn left" href="{% url 'calendar' owner.id %}">Back to Calendar</a>
            
            {% if is_friend %}
            {% else %}
                <a class="btn right" href="{% url 'event_edit' event.id %}">Edit Event</a>
                <a class="btn center" href="{% url 'delete_event' user.id event.id%}" role="button" style="background-color: red !important;">Delete</a>
            {% endif %}
        </div>
        
    </div>



    
</body>

</html>
{% endblock %}

project/home/templates/game_list.html
{% extends "base_template.html" %}

{% block content %}

<!-- Ensures success messages display on the game_list page when user deletes a game. -->
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}

<!-- Table displaying user's games. -->
<h2>Your Games</h2>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Platform</th>
            <th>Genre</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for game in games %}
        <tr>
            <td>{{ game.name }}</td>
            <td>{{ game.get_platform_display }}</td>
            <td>{{ game.genre }}</td>
            <td>
                <a href="{% url 'edit_game' game.id %}" class="btn" >Edit</a> |
                <a href="{% url 'delete_game' game.id %}" class="btn" style="background-color: red !important;" >Delete</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">You have no games added.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<br><br>
<div class="button-container">
    <a class="btn" href="{% url 'calendar' user.id %}">Back to Calendar</a>
    <a class="btn" href="{% url 'create_game' %}">Add a New Game</a>
</div>
{% endblock %}

project/home/templates/todo_list.html
{% extends "base_template.html" %}

{% block title %}TODO LIST{% endblock %}

{% load static %}

{% block content %}
<header class="header">
    <!-- Game Plan Calendar logo or other content -->
    <h1>Upcoming Events for Today</h1>
</header>

<div class="todo-list-page"> <!-- Specific class for this page -->
    {% if games_with_events %}
        <div class="main-content">
            {% for game_name, game_data in games_with_events.items %}
                <div class="game-section">
                    <!-- Display Game Image -->
                    {% if game_data.game.picture_link %}
                        <img src="{{ game_data.game.picture_link }}" alt="Image for {{ game_name }}" class="game-image">
                    {% endif %}

                    <h2>{{ game_name }}</h2>
                    <ul class="event-list">
                        {% for event in game_data.events %}
                            <li class="event-item">
                                <div class="event-details">
                                    <p><strong>Title:</strong> 
                                        <a href="{% url 'event_detail' event.id %}" style="color: #4CAF50; text-decoration: none;">
                                            {{ event.title }}
                                        </a>
                                    </p>
                                    <p><strong>Description: {{ event.description }}</strong></p>
                                    <p><strong>Priority: {{ event.get_priority_display }}</strong></p>
                                    <p><strong>Start Time: {{ event.start_time|date:"F j, Y, g:i a" }}</strong></p>
                                    <p><strong>End Time: {{ event.end_time|date:"F j, Y, g:i a" }}</strong></p>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No events scheduled for today.</p>
    {% endif %}
</div>
{% endblock %}